### ISSUE TITLE
add tests for charting missing or bad data

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/comport#20]

**Comment by creade** [comment]
Cases for data ingestion:

[ ] missing values
[ ] blank roles
[ ] fuzzed data
[ ] datatype mismatch
[ ] data to be cleaned
[ ] casing
[ ] abbreviation

**Comment by creade** [comment]
Cases for data to be rendered:
- [ ] new column values
- [ ] proper nulls and blanks
- [ ] unfilled buckets
- [ ] extreme cases for "other"
- [ ] incomplete time span
- [ ] gaps in time
- [ ] sparseness in time span

**Comment by creade** [comment]
Closed by mutators and json test client
