### ISSUE TITLE
Add blocks for schema pages

### ISSUE THREAD

**Issue by creade** [codeforamerica/comport#22]

**Comment by tmaybe** [comment]
@creade can you give me more detail on this issue?

**Comment by creade** [comment]
Currently text content on the dataset pages (the ones with the graphs) is editable by department users. That's not true for data schema pages which are at the moment, totally static. I have a branch (https://github.com/codeforamerica/comport/tree/schema-custom) that adds the edit ability for the complaints schema page but the other two need to be brought along.
