### ISSUE TITLE
Improve dataset pages layout

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/comport#24]
For complaints, OIS, and use of force pages, adjust content to have:

1. Clear big action button to get data (leads to schema page)
2. Table of Contents for charts
3. Intro text
4. Each chart

![screen shot 2015-12-17 at 3 32 43 pm](https://cloud.githubusercontent.com/assets/451510/11885102/7339dc8a-a4d3-11e5-8c36-ea953c7a1873.png)

**Comment by bengolder** [comment]
Made some initial changes for the top of the page

![screen shot 2016-01-07 at 2 24 09 pm](https://cloud.githubusercontent.com/assets/451510/12184484/567a19a2-b54a-11e5-9c07-8e8ce05e3b77.png)

**Comment by bengolder** [comment]
Made changes for mobile.
This is now the laptop version
![screen shot 2016-01-08 at 6 19 55 pm](https://cloud.githubusercontent.com/assets/451510/12213818/98bc0290-b634-11e5-946c-0cd25747ba04.png)

and the mobile version:
![screen shot 2016-01-08 at 6 20 06 pm](https://cloud.githubusercontent.com/assets/451510/12213817/98a9ca4e-b634-11e5-8b04-412c03a99ede.png)

**Comment by creade** [comment]
Closed with Pull Request #30?

**Comment by bengolder** [comment]
Additional requests:

- [ ] make the side nav smaller.
- [ ] the first viz needs to be above the fold

**Comment by bengolder** [comment]
These are resolved with PRs #37 and #39

**Comment by bengolder** [comment]
Closed with merging of #37 and #39
