### ISSUE TITLE
Display time span for each chart

### ISSUE THREAD

**Issue by creade** [codeforamerica/comport#36]

**Comment by bengolder** [comment]
![screen shot 2016-01-12 at 5 24 38 pm](https://cloud.githubusercontent.com/assets/451510/12282236/76d5c556-b951-11e5-9e24-7cb8ea490d5f.png)
![screen shot 2016-01-12 at 5 24 22 pm](https://cloud.githubusercontent.com/assets/451510/12282234/76d3ea42-b951-11e5-82e2-7341d110bd75.png)
![screen shot 2016-01-12 at 5 24 10 pm](https://cloud.githubusercontent.com/assets/451510/12282238/76d7108c-b951-11e5-8be5-0bf243802228.png)
![screen shot 2016-01-12 at 5 24 05 pm](https://cloud.githubusercontent.com/assets/451510/12282237/76d6b5e2-b951-11e5-88a4-88e0e524d831.png)
![screen shot 2016-01-12 at 5 23 28 pm](https://cloud.githubusercontent.com/assets/451510/12282235/76d428ae-b951-11e5-9d27-7298b6586af8.png)

**Comment by bengolder** [comment]
Looks like #4 is the winner.

**Comment by bengolder** [comment]
Closed with #37
