### ISSUE TITLE
Extreme Other cases

### ISSUE THREAD

**Issue by creade** [codeforamerica/comport#44]
The `FuzzedDataMutator` will provide a very long tail of random values and an "Other" value of 0:
![image](https://cloud.githubusercontent.com/assets/356576/12465277/1ae348f4-bf82-11e5-86d0-29c0a60f4d51.png)

**Comment by tmaybe** [comment]
@creade can you say more about this? Is the `FuzzedDataMutator` used anywhere in production? Is this about providing realistic test data?

**Comment by creade** [comment]
So we have the `test_client` target that can be run against a running app on localhost for testing. Normally `test_client` will make a whole bunch of randomized test incidents similar to production data (i.e. using know field values.) There are a series of mutators that can be run on the data before it is posted to the app though. We built these mainly to see how the ui would function under data values not present in the prod data we had access to, especially extreme cases. `FuzzedDataMutator` is one of those and can be turned on by uncommenting https://github.com/codeforamerica/comport/blob/master/manage.py#L220 and adding `fuzzed_data_mutator` to the array here: https://github.com/codeforamerica/comport/blob/master/manage.py#L227
then running `python manage.py test_client`

The test data generated will not be realistic but it will push some assumptions made by the UI. This particular issue is about how the "Other" bucket is calculated when every value represents less than the threshold set here: https://github.com/codeforamerica/comport/blob/b13278f9000924ab02e99d7ee0873b7b22e1e16a/comport/static/js/charts.js#L242

Which in the end is really just saying that if the Other bucket is empty we shouldn't show it:
![image](https://cloud.githubusercontent.com/assets/356576/13100254/f23a3682-d4ef-11e5-86e4-6d1888a35066.png)
