### ISSUE TITLE
Failing Cleaners Tests

### ISSUE THREAD

**Issue by keith24** [codeforamerica/comport#82]
I just started the open source game, so forgive me if I'm doing it wrong.  

```
$ python manage.py test
...
tests/test_cleaners.py::TestCleaners::test_unknown_resident_weapon_returned FAILED   
                                                                                     
===================================== FAILURES ======================================
________________ TestCleaners.test_unknown_resident_weapon_returned _________________
                                                                                     
self = <tests.test_cleaners.TestCleaners instance at 0x7f1847217758>                 
                                                                                     
    def test_unknown_resident_weapon_returned(self):                                 
        ''' Cleaning an unknown weapon returns the same value passed.                
            '''                                                                      
        weapon = "Suspect - Lewd Nebulosity "                                        
>       cleaned = Cleaners.resident_weapon_used(weapon)                              
E       TypeError: unbound method resident_weapon_used() must be called with Cleaners instance as first argument (got str instance instead)                               
                                                                                     
tests/test_cleaners.py:11: TypeError                                                 
!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!
======================== 1 failed, 5 passed in 1.63 seconds =========================
```

It seems like the Cleaners functions, like `residen_weapon_used()` should be performed on an instance, not the class.  

I would think this could be fixed by adding `@staticmethod` to each of the Cleaners functions.  Or by creating a Cleaners instance in TestCleaners: 

```
class TestCleaners:
    cleaner = Cleaners()

    def test_unknown_resident_weapon_returned(self):
        ''' Cleaning an unknown weapon returns the same value passed.
        '''
        weapon = "Suspect - Lewd Nebulosity "
        cleaned = cleaner.resident_weapon_used(weapon)
        assert cleaned == weapon
...
```

**Comment by tmaybe** [comment]
Good catch @keith24, thank you. Can you try the branch `create-cleaners-instances-#82` and verify that the cleaner tests pass for you?

You're doing fine in the open-source game :) I appreciate you reviewing our code.

**Comment by keith24** [comment]
No problem.  Already learning lots: 

> The concept of “unbound methods” has been removed from the language. When referencing a method as a class attribute, you now get a plain function object.

aaaaand I've been using python 2 this whole time.

**Comment by tmaybe** [comment]
Ah, that makes sense. Right now we only mention that it's a Python 3 project on one line in the README. I'll start an issue to remind myself to make it more explicit.

**Comment by keith24** [comment]
So ahem, yes, now all the tests are passing, but I did have to tweak two things.  

Firstly, my ide, [cloud9](c9.io) only lets me run on port 8080.  So I added this to `settings.py`:

```
class Config(object):
    PORT = 8080 # port configuration
    SECRET_KEY = os_env.get('COMPORT_SECRET', 'comport-secret-key')
    BASE_URL = os_env.get('BASE_URL', 'http://localhost:'+str(PORT)+'/')
```

Would it be rude to merge such a thing?  I'd imagine changing the port is something that might come up from time to time, and could be worth putting in the config.  Could even be worth accepting it as a argument to `manage.py server`

The other thing is that the database only worked with the URI set to `postgresql:///comport?client_encoding=utf8`.  It's a linux thing, I guess.  

I don't mind changing these settings every time I commit changes... if that's how it should be done.  How do contributors usualy set such local preferences?

**Comment by tmaybe** [comment]
Thanks @keith24. For your first issue, you can specify the port when you start the server like so:

`python manage.py server -p 8080`

That's a `flask` thing. You can type `python manage.py server -?` to see all the options.

Could you start a separate issue for the postgres encoding problem you're describing?
