### ISSUE TITLE
document visualizations data format

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/comport#88]
Log data formats to console, copy, paste, anonymize, and write an explanation. Put the format documentation in this repo's wiki or in a markdown file.

**Comment by bengolder** [comment]
I'm going to document them here and then transfer them over to the wiki afterwards.

**Comment by bengolder** [comment]
complaints-by-month
```
[
  {"count": 17, "month": "Fri May 01 2015 00:00:00 GMT-0700 (PDT)"},
  {"count": 36, "month": "Fri Jun 01 2015 00:00:00 GMT-0700 (PDT)"},
  ...
]
```

complaints-by-precinct
```
[
  {"count": 57, "type": "East District"},
  ...
]
```

complaints-by-demographic (demogrphics matrix)
This is implemented with d3.map objects
```
var map = d3.map({
    "Asian": d3.map({})
    "Black": d3.map({
        "Black": {
            "count": 13,
            "percent": 0.05726872246696035
            },
        "Hispanic": {},
        "Other": {},
        "Unknown": {},
        "White": {},
        })
    "Hispanic": d3.map({})
    "Other": d3.map({})
    "Unknown": d3.map({})
    "White": d3.map({})
});
map.officerRaceTotals = d3.map({
        "Black": {
            "count": 45,
            "percent": 0.19823788546255505
            },
        "Hispanic": {},
        "Other": {},
        "Unknown": {},
        "White": {},

    })
```

complaints-by-disposition
```
[
  {"count": 83, "type": "Not Sustained"},
  ...
]
```

complaints-by-allegation
```
[
  {"count": 74, "type": "Rude, Demeaning, or Affronting Language"},
  ...
]
```

complaints-by-allegation-type
```
[
  {"count": 74, "type": "Rude, Demeaning, or Affronting Language"},
  ...
]
```

officer-demographics
```
[
  {"count": 85917, "entity": "city",
    "percent": 0.08607546493093786, "race": "Hispanic" },
  ...
  {"count": 40, "entity": "department",
    "percent": 0.025268477574226154, "race": "Hispanic" },
  ...
]
```

complaints-by-officer
```
[
  {"count": 74, "label": "Officers with 1 complaint"},
  ...
]
```

**Comment by bengolder** [comment]
A few caveats:
* The d3 maps in complaints-by-demographic are used essentially as key-value stores that are cleaner and with a better API than a standard Javascript Object.
* all of these actually include an `"incidents"` attribute that I did not document here. This is included for debugging purposes (it contains an array of all the incidents corresponding to a particular bucket or group), and should not be used for drawing the charts.
